default:
  image:
    name: dotnet-sdk:7.0
    pull_policy: if-not-present

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Building WebApp... "
    - dotnet build
    - echo "Build complete."

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests..."
    - dotnet test
    - echo "Unit test Completed"


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
    - cd sample-api/
    - dotnet run
    - echo "Application Deployed Successfully!!"
